CELL_SIZE = 20
CELL_WIGHT = 54
CELL_HEIGHT = 30
SPACE = 80
WIGHT = CELL_SIZE * CELL_WIGHT + 2 * SPACE
HEIGHT = CELL_SIZE * CELL_HEIGHT + 2 * SPACE
FPS = 60
WALL_SYMBOL = '#'
EAT_SYMBOL = '-'
BOOST_SYMBOL = '*'
EAT_COST = 20
BOOST_COST = 50
MOVE_SPEED = CELL_SIZE // 16
IMAGE_NAME_PACMAN_1 = 'image/pac-man1.png'
IMAGE_NAME_PACMAN_2 = 'image/pac-man2.png'
IMAGE_NAME_RED_GHOST_1 = 'image/red_ghost.png'
IMAGE_NAME_RED_GHOST_2 = 'image/red_ghost.png'
IMAGE_NAME_PINK_GHOST_1 = 'image/pink_ghost.png'
IMAGE_NAME_PINK_GHOST_2 = 'image/pink_ghost.png'
IMAGE_NAME_ORANGE_GHOST_1 = 'image/orange_ghost.png'
IMAGE_NAME_ORANGE_GHOST_2 = 'image/orange_ghost.png'
IMAGE_NAME_BLUE_GHOST_1 = 'image/blue_ghost.png'
IMAGE_NAME_BLUE_GHOST_2 = 'image/blue_ghost.png'
IMAGE_LIVING_HEART = 'image/living_heart2.png'
IMAGE_DEAD_HEART = 'image/dead_heart.png'
MAX_HP = 3
